### ISSUE TITLE
path.inShadow not found (babel 7 support?)

### ISSUE THREAD

**Issue by thescientist13** [WebReflection/babel-plugin-transform-builtin-classes#16]
Hey, thanks for this plugin!  

I think now that Babel 7 is out, this plugin might need to be changed to support it?  Currently the error I'm seeing is:
```shell
ERROR in ./test.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: path.inShadow is not a function
    at ReplaceSupers.ReturnStatement (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/babel-helper-replace-supers/lib/index.js:55:15)
    at NodePath._call (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/owenbuckley/Workspace/project-evergreen/repos/todo-app/node_modules/@babel/traverse/lib/context.js:118:16)
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:1981 ./test test[1]
```

Using _.babelrc_ in conjunection with **webpack** + **babel-loader**
```shell
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    "babel-plugin-transform-es2015-classes",
    ["babel-plugin-transform-builtin-classes", {
      "globals": ["Array", "Error", "HTMLElement"]
    }]
  ]
}
```

Thanks and let me know if you need anymore info!

**Comment by thescientist13** [comment]
sorry, I actually just tried it without `"babel-plugin-transform-es2015-classes"` and seems like that got the build working.  

Since I'm using `@babel/preset-env` seems like I don't need to use them both them then?

**Comment by WebReflection** [comment]
@thescientist13 Babel 7 included this plugin in core so you don't need it anymore.

**Comment by thescientist13** [comment]
Thanks, and good to know.

I did end up needing this just to support a 3rd party dependency (`LitElement`) but I was able to remove all the others.  Seems to be working great.  

Thanks for all the help and making this plugin!

**Comment by WebReflection** [comment]
With HyperHTMLElement you'd do great right away

**Comment by thescientist13** [comment]
Good to know, and yeah, definitely have hyperHTML on my list of things to try out.  Thanks again for all your great contributions to the community!  🌟
